# Generated by Django 3.0.5 on 2020-07-19 10:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import profanity.validators
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FeaturenBugCategory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'verbose_name': 'Category of Bugs/Features',
            },
        ),
        migrations.CreateModel(
            name='FeaturenBugStatus',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'verbose_name': 'Status of Bugs/Features',
            },
        ),
        migrations.CreateModel(
            name='FeaturenBug',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('Feature', 'Feature Request'), ('Bug', 'Bug Report')], max_length=7)),
                ('title', models.CharField(max_length=300, validators=[profanity.validators.validate_is_profane])),
                ('text', models.TextField(max_length=2000, validators=[profanity.validators.validate_is_profane])),
                ('image', models.ImageField(blank=True, help_text='Photos of Bug Or Feature you Request! In case of please provide and Image', null=True, upload_to='featurenbug_images')),
                ('date_posted', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('slug', models.SlugField(max_length=150, null=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='featurebug.FeaturenBugCategory')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='featurebug.FeaturenBugStatus')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Feature Requests and Bug Reports',
                'get_latest_by': '-date_posted',
            },
        ),
    ]
