# Generated by Django 3.0.5 on 2020-05-20 11:14

from django.db import migrations, models
import profanity.validators


class Migration(migrations.Migration):

    dependencies = [
        ('featurebug', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='featurenbug',
            name='text',
            field=models.TextField(max_length=2000, validators=[profanity.validators.validate_is_profane]),
        ),
        migrations.AlterField(
            model_name='featurenbug',
            name='title',
            field=models.CharField(max_length=300, validators=[profanity.validators.validate_is_profane]),
        ),
    ]
