version: "3.3"

services:
  web:
    container_name: hashx_application
    build: ./hashx
    command: gunicorn hashx.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - ./hashx/:/usr/src/app/
      - static_volume:/usr/src/app/static
      - media_volume:/usr/src/app/media
    expose:
      - 8000
    env_file:
      - ./hashx/.env
    depends_on:
      - db

  db:
    container_name: hashx_database
    image: postgres:12.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./hashx/.env.db

  nginx:
    container_name: hashx_webserver
    build: ./webserver
    volumes:
      - static_volume:/usr/src/app/static
      - media_volume:/usr/src/app/media
    ports:
      - 80:80
    depends_on:
      - web

volumes:
  postgres_data:
  static_volume:
  media_volume:
