# Generated by Django 3.0.5 on 2020-07-10 19:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import profanity.validators
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemCategory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='ItemStatus',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Status',
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, validators=[profanity.validators.validate_is_profane])),
                ('type', models.CharField(choices=[('Lost', 'Lost'), ('Found', 'Found')], max_length=5)),
                ('details', models.TextField(max_length=1000, validators=[profanity.validators.validate_is_profane])),
                ('image', models.ImageField(blank=True, null=True, upload_to='lostandfound_photos')),
                ('contact_details', models.CharField(max_length=200, validators=[profanity.validators.validate_is_profane])),
                ('date_posted', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_reviewed', models.BooleanField(default=False)),
                ('published', models.BooleanField(default=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='lostfound.ItemCategory')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='lostfound.ItemStatus')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Item', related_query_name='Item', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Lost and Found Items',
            },
        ),
    ]
