# Generated by Django 3.0.5 on 2020-05-20 11:14

from django.db import migrations, models
import profanity.validators


class Migration(migrations.Migration):

    dependencies = [
        ('lostfound', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='contact_details',
            field=models.CharField(max_length=200, validators=[profanity.validators.validate_is_profane]),
        ),
        migrations.AlterField(
            model_name='item',
            name='details',
            field=models.TextField(max_length=1000, validators=[profanity.validators.validate_is_profane]),
        ),
        migrations.AlterField(
            model_name='item',
            name='name',
            field=models.CharField(max_length=150, validators=[profanity.validators.validate_is_profane]),
        ),
    ]
