# Generated by Django 3.0.5 on 2020-05-02 08:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('about', models.CharField(max_length=1000, null=True)),
                ('delivery', models.NullBooleanField()),
                ('in_campus', models.BooleanField(default=True)),
                ('image', models.ImageField(upload_to='shop_profile')),
                ('stars', models.DecimalField(decimal_places=2, default=0.0, max_digits=3)),
                ('owner', models.CharField(max_length=200, null=True)),
                ('phone_no', models.CharField(max_length=10, null=True)),
                ('time_open', models.TimeField()),
                ('time_close', models.TimeField()),
                ('paytm_id', models.CharField(max_length=100, null=True)),
                ('location', models.URLField()),
                ('menu_image', models.ImageField(upload_to='shop_menu_image')),
            ],
        ),
        migrations.CreateModel(
            name='ShopItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('image', models.ImageField(null=True, upload_to='shopitem')),
                ('price', models.PositiveIntegerField()),
                ('stars', models.DecimalField(decimal_places=2, default=0.0, max_digits=3)),
                ('shop', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop.Shop')),
            ],
        ),
        migrations.CreateModel(
            name='ShopType',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=50)),
                ('image', models.ImageField(null=True, upload_to='shoptypes')),
            ],
        ),
        migrations.CreateModel(
            name='ShopReview',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('stars', models.DecimalField(decimal_places=2, default=0.0, max_digits=3)),
                ('review', models.CharField(max_length=256)),
                ('date_posted', models.DateTimeField(default=django.utils.timezone.now)),
                ('shop', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop.Shop')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ShopItemReview',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('stars', models.DecimalField(decimal_places=2, default=0.0, max_digits=3)),
                ('review', models.CharField(max_length=256)),
                ('date_posted', models.DateTimeField(default=django.utils.timezone.now)),
                ('shop_item', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop.ShopItem')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='shop',
            name='type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop.ShopType'),
        ),
    ]
