# Generated by Django 3.0.5 on 2020-05-20 11:14

from django.db import migrations, models
import profanity.validators


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopitemreview',
            name='review',
            field=models.CharField(max_length=256, validators=[profanity.validators.validate_is_profane]),
        ),
        migrations.AlterField(
            model_name='shopreview',
            name='review',
            field=models.CharField(max_length=256, validators=[profanity.validators.validate_is_profane]),
        ),
    ]
