# Generated by Django 3.1 on 2022-01-15 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='delivery',
            field=models.BooleanField(null=True),
        ),
    ]
