# Generated by Django 3.1 on 2022-02-01 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_auto_20220115_2154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='delivery',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
