# Generated by Django 3.0.5 on 2020-07-13 15:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0003_auto_20200713_2034'),
        ('acad', '0002_auto_20200713_2034'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lecture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meetingURL', models.URLField(blank=True, null=True)),
                ('isCompleted', models.BooleanField(default=True)),
                ('recordingURL', models.URLField(blank=True, null=True)),
                ('time', models.DateTimeField()),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='acad.Batch')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='acad.Course')),
                ('instructor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Instructor')),
            ],
        ),
    ]
