# Generated by Django 3.0.5 on 2020-07-10 19:48

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('society', '0001_initial'),
        ('users', '0001_initial'),
        ('timetable', '0001_initial'),
        ('hostel', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PermiCategory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='PermiStatus',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Permi',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('in_time', models.DateTimeField()),
                ('out_time', models.DateTimeField()),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('comment', models.TextField(max_length=500)),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='permission.PermiStatus')),
            ],
        ),
        migrations.CreateModel(
            name='SocietyPermi',
            fields=[
                ('permi_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='permission.Permi')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='timetable.Location')),
                ('society', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='society.Society')),
            ],
            bases=('permission.permi',),
        ),
        migrations.CreateModel(
            name='GirlsPermi',
            fields=[
                ('permi_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='permission.Permi')),
                ('destination', models.TextField(max_length=256, null=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='permission.PermiCategory')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='hostel.Room')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='users.Student')),
            ],
            bases=('permission.permi',),
        ),
    ]
