# Generated by Django 3.0.5 on 2020-07-19 10:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import profanity.validators
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('buzz', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComplaintStatus',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='ComplaintTypes',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Hostel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=1)),
                ('about', models.TextField(max_length=2000, null=True)),
                ('warden_name', models.CharField(max_length=100)),
                ('caretaker_name', models.CharField(max_length=100)),
                ('caretaker_contact', models.CharField(help_text='Contact phone number', max_length=10)),
                ('capacity', models.PositiveIntegerField(blank=True, null=True)),
                ('slug', models.SlugField(blank=True, max_length=250, null=True)),
                ('image', models.ImageField(null=True, upload_to='hostel_images')),
                ('b_start', models.TimeField(null=True)),
                ('b_end', models.TimeField(null=True)),
                ('l_start', models.TimeField(null=True)),
                ('l_end', models.TimeField(null=True)),
                ('d_start', models.TimeField(null=True)),
                ('d_end', models.TimeField(null=True)),
                ('discussion', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='buzz.Category')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hostel', related_query_name='hostel', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Hostels',
            },
        ),
        migrations.CreateModel(
            name='MessUnit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('day', models.CharField(choices=[('MON', 'Monday'), ('TUE', 'Tuseday'), ('WED', 'Wednesday'), ('THR', 'Thursday'), ('FRI', 'Friday'), ('SAT', 'Saturday'), ('SUN', 'Sunday')], max_length=3)),
                ('type', models.CharField(choices=[('Breakfast', 'Breakfast'), ('Lunch', 'Lunch'), ('Dinner', 'Dinner')], max_length=20)),
                ('food', models.TextField(max_length=200)),
                ('image', models.ImageField(blank=True, null=True, upload_to='messunit')),
                ('slug', models.SlugField(blank=True, max_length=100, null=True)),
                ('mess', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='MessUnit', related_query_name='MessUnit', to='hostel.Hostel')),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('wing', models.CharField(editable=False, max_length=3)),
                ('num', models.PositiveIntegerField(editable=False)),
                ('hostel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hostel.Hostel')),
            ],
        ),
        migrations.CreateModel(
            name='MessUnitComment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('stars', models.PositiveIntegerField()),
                ('comment', models.CharField(blank=True, max_length=200, null=True, validators=[profanity.validators.validate_is_profane])),
                ('date_posted', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('messunit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='MessUnit', related_query_name='MessUnit', to='hostel.MessUnit')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='MessUnitComment', related_query_name='MessUnitComment', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date_posted'],
            },
        ),
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('subject', models.CharField(max_length=200, validators=[profanity.validators.validate_is_profane])),
                ('description', models.TextField(max_length=1000, validators=[profanity.validators.validate_is_profane])),
                ('image', models.ImageField(blank=True, null=True, upload_to='hostel_complaint')),
                ('avail_start', models.TimeField()),
                ('avail_end', models.TimeField()),
                ('date_posted', models.DateTimeField(default=django.utils.timezone.now)),
                ('comments', models.TextField(max_length=300, validators=[profanity.validators.validate_is_profane])),
                ('slug', models.SlugField(blank=True, max_length=100, null=True)),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Complaint', related_query_name='Complaint', to='hostel.ComplaintStatus')),
                ('types', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Complaint', related_query_name='Complaint', to='hostel.ComplaintTypes')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='complaint', related_query_name='complaint', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date_posted'],
            },
        ),
    ]
