# Generated by Django 3.0.5 on 2020-05-10 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hostel', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hostel',
            old_name='disscussion',
            new_name='discussion',
        ),
    ]
