# Generated by Django 3.0.5 on 2020-07-18 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostel', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hostel',
            name='caretaker_contact',
            field=models.CharField(help_text='Contact phone number', max_length=11),
        ),
    ]
