# Generated by Django 3.0.5 on 2020-05-11 03:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hostel', '0002_auto_20200509_0747'),
        ('hostel', '0002_auto_20200510_1515'),
    ]

    operations = [
    ]
