# Generated by Django 3.0.5 on 2020-05-20 11:14

from django.db import migrations, models
import profanity.validators


class Migration(migrations.Migration):

    dependencies = [
        ('hostel', '0003_merge_20200511_0310'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='comments',
            field=models.TextField(max_length=300, validators=[profanity.validators.validate_is_profane]),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='description',
            field=models.TextField(max_length=1000, validators=[profanity.validators.validate_is_profane]),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='subject',
            field=models.CharField(max_length=200, validators=[profanity.validators.validate_is_profane]),
        ),
        migrations.AlterField(
            model_name='messunitcomment',
            name='comment',
            field=models.CharField(blank=True, max_length=200, null=True, validators=[profanity.validators.validate_is_profane]),
        ),
    ]
