# Generated by Django 3.0.5 on 2020-07-18 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostel', '0003_auto_20200718_1300'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hostel',
            name='name',
            field=models.CharField(max_length=3),
        ),
    ]
