# Generated by Django 3.1 on 2022-01-15 17:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import profanity.validators
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hostel', '0004_auto_20200718_1301'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='hostel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='complaint', related_query_name='complaint', to='hostel.hostel'),
        ),
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200, validators=[profanity.validators.validate_is_profane])),
                ('description', models.TextField(max_length=1000, validators=[profanity.validators.validate_is_profane])),
                ('date_posted', models.DateTimeField(default=django.utils.timezone.now)),
                ('date_updated', models.DateTimeField(default=django.utils.timezone.now)),
                ('hostel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='announcement', related_query_name='announcement', to='hostel.hostel')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='announcement', related_query_name='announcement', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
