# Generated by Django 3.1 on 2022-01-16 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostel', '0005_auto_20220115_2323'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='announcement',
            name='hostel',
        ),
        migrations.AddField(
            model_name='announcement',
            name='hostel',
            field=models.ManyToManyField(blank=True, related_name='announcement', related_query_name='announcement', to='hostel.Hostel'),
        ),
    ]
