# Generated by Django 3.0.5 on 2020-07-19 10:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import profanity.validators
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('acad', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Verification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(blank=True, default=None, max_length=254, null=True, unique=True)),
                ('rollno', models.IntegerField(null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('image', models.ImageField(default='default.jpg', upload_to='profile_pics')),
                ('bio', models.CharField(max_length=256, validators=[profanity.validators.validate_is_profane])),
                ('rollno', models.IntegerField(blank=True, null=True)),
                ('points', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('gender', models.CharField(choices=[('M', 'MALE'), ('F', 'FEMALE'), ('T', 'TRANSGENDER')], max_length=1)),
                ('created_date', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('token', models.UUIDField(default=uuid.uuid4)),
                ('matched_in_database', models.BooleanField(default=False)),
                ('invited_code', models.CharField(max_length=8, null=True)),
                ('batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='acad.Batch')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='acad.Branch')),
                ('firstyearbatch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='acad.FirstYearBatch')),
                ('starred_files', models.ManyToManyField(blank=True, to='acad.File')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='student', related_query_name='student', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Instructor',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('course_codinator', models.BooleanField(blank=True, default=None, null=True)),
                ('email', models.EmailField(blank=True, default=None, max_length=254, null=True)),
                ('office', models.CharField(max_length=5)),
                ('role', models.CharField(max_length=100)),
                ('specialisation', models.CharField(max_length=500)),
                ('biography', models.CharField(max_length=10000)),
                ('created_date', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('batches', models.ManyToManyField(to='acad.Batch')),
                ('course', models.ManyToManyField(to='acad.Course')),
                ('firstyearbatches', models.ManyToManyField(to='acad.FirstYearBatch')),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='instructor', related_query_name='instructor', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Instructor',
                'verbose_name_plural': 'Instructors',
            },
        ),
    ]
