# Generated by Django 3.0.5 on 2020-07-19 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='instructor',
            name='department',
            field=models.CharField(blank=True, choices=[('CHEM', 'Chemical'), ('BT', 'Biotechnology'), ('CIV', 'Civil'), ('COMP', 'Computer'), ('EI', 'Electrical and Instrumentation'), ('EC', 'Electronics and Communication'), ('MECH', 'Mechanical'), ('SCBC', 'School of Chemistry and Biochemistry'), ('SEE', 'School of Energy and Environment'), ('SMSS', 'School of Humanities & Social Sciences'), ('SOM', 'School of Mathematics'), ('SPMS', 'School of Physics & Materials Science')], max_length=50, null=True),
        ),
    ]
