# Generated by Django 3.0.5 on 2020-07-12 19:09

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('acad', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Verification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(blank=True, default=None, max_length=254, null=True, unique=True)),
                ('rollno', models.IntegerField(null=True, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='student',
            name='matched_in_database',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='instructor',
            name='biography',
            field=models.CharField(max_length=10000),
        ),
        migrations.AlterField(
            model_name='instructor',
            name='role',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='instructor',
            name='specialisation',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='student',
            name='batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='acad.Batch'),
        ),
        migrations.AlterField(
            model_name='student',
            name='firstyearbatch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='acad.FirstYearBatch'),
        ),
        migrations.AlterField(
            model_name='student',
            name='rollno',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
