# Generated by Django 3.0.5 on 2020-07-13 23:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('acad', '0001_initial'),
        ('users', '0002_auto_20200713_0039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='acad.Branch'),
        ),
    ]
