# Generated by Django 3.0.5 on 2020-07-13 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acad', '0002_auto_20200713_2034'),
        ('users', '0002_auto_20200713_0039'),
    ]

    operations = [
        migrations.AddField(
            model_name='instructor',
            name='batches',
            field=models.ManyToManyField(to='acad.Batch'),
        ),
        migrations.AddField(
            model_name='instructor',
            name='firstyearbatches',
            field=models.ManyToManyField(to='acad.FirstYearBatch'),
        ),
    ]
