# Generated by Django 3.0.5 on 2020-07-21 20:23

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_instructor_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='instructor',
            name='is_email_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='instructor',
            name='token',
            field=models.UUIDField(default=uuid.uuid4),
        ),
    ]
