# Generated by Django 3.0.5 on 2020-05-05 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acad', '0004_file_filetags_filetype'),
        ('users', '0002_auto_20200504_2238'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='starred_files',
            field=models.ManyToManyField(to='acad.File'),
        ),
    ]
