# Generated by Django 3.0.5 on 2020-06-18 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20200715_1251'),
    ]

    operations = [
        migrations.AddField(
            model_name='instructor',
            name='department',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
