# Generated by Django 3.0.5 on 2020-05-11 19:05

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_student_starred_files'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='rollno',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='token',
            field=models.UUIDField(default=uuid.uuid4),
        ),
    ]
