# Generated by Django 3.0.5 on 2020-07-21 20:28
from django.db import migrations, models
import uuid


def forwards(apps, schema_editor):
    Instructor = apps.get_model('users', 'Instructor')
    for i in Instructor.objects.all():
        i.token = uuid.uuid4()
        i.save()


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20200722_0153'),
    ]

    operations = [
        migrations.RunPython(forwards),

        migrations.AlterField(
            model_name='instructor',
            name='token',
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
