# Generated by Django 3.0.8 on 2020-07-25 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='instructor',
            name='code',
            field=models.CharField(default='AAA', max_length=3),
        ),
    ]
