# Generated by Django 3.0.5 on 2020-07-19 06:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20200714_0512'),
        ('users', '0003_auto_20200713_2301'),
    ]

    operations = [
    ]
