# Generated by Django 3.0.5 on 2020-05-20 11:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import profanity.validators


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0004_auto_20200511_1905'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='bio',
            field=models.CharField(max_length=256, validators=[profanity.validators.validate_is_profane]),
        ),
        migrations.AlterField(
            model_name='student',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='student', related_query_name='student', to=settings.AUTH_USER_MODEL, validators=[profanity.validators.validate_is_profane]),
        ),
    ]
