# Generated by Django 3.0.5 on 2020-05-21 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acad', '0008_auto_20200519_0013'),
        ('users', '0004_auto_20200511_1905'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='starred_files',
            field=models.ManyToManyField(null=True, to='acad.File'),
        ),
    ]
