# Generated by Django 3.0.5 on 2020-07-18 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acad', '0002_auto_20200719_0527'),
        ('users', '0004_auto_20200714_0512'),
    ]

    operations = [
        migrations.AddField(
            model_name='instructor',
            name='batches',
            field=models.ManyToManyField(to='acad.Batch'),
        ),
        migrations.AddField(
            model_name='instructor',
            name='firstyearbatches',
            field=models.ManyToManyField(to='acad.FirstYearBatch'),
        ),
    ]
