# Generated by Django 3.0.5 on 2020-07-19 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20200719_0527'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='can_invite',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='student',
            name='invited_code',
            field=models.CharField(max_length=8, null=True),
        ),
    ]
