# Generated by Django 3.0.5 on 2020-05-21 15:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0006_auto_20200521_1514"),
        ("users", "0006_auto_20200521_0724"),
    ]

    operations = []
