# Generated by Django 3.0.5 on 2020-05-21 16:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20200521_1835'),
        ('users', '0005_auto_20200520_1114'),
    ]

    operations = [
    ]
