# Generated by Django 3.0.5 on 2020-07-19 05:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20200719_0559'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='can_invite',
        ),
    ]
