# Generated by Django 3.0.5 on 2020-05-22 06:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_merge_20200521_1541'),
        ('users', '0008_auto_20200521_2214'),
    ]

    operations = [
    ]
