# Generated by Django 3.0.5 on 2020-05-27 05:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_merge_20200522_1218'),
        ('users', '0006_auto_20200520_1751'),
    ]

    operations = [
    ]
