# Generated by Django 3.0.5 on 2020-06-25 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_merge_20200527_0559'),
    ]

    operations = [
        migrations.AddField(
            model_name='instructor',
            name='biography',
            field=models.CharField(default=None, max_length=500),
        ),
        migrations.AddField(
            model_name='instructor',
            name='role',
            field=models.CharField(default=None, max_length=50),
        ),
        migrations.AddField(
            model_name='instructor',
            name='specialisation',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
