# Generated by Django 3.0.5 on 2020-07-01 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_auto_20200625_1754'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instructor',
            name='biography',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='instructor',
            name='role',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='instructor',
            name='specialisation',
            field=models.CharField(max_length=100),
        ),
    ]
