# Generated by Django 3.0.8 on 2020-07-05 07:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_auto_20200704_0728'),
        ('users', '0012_auto_20200705_0814'),
    ]

    operations = [
    ]
