# Generated by Django 3.0.5 on 2020-07-05 19:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_merge_20200705_1309'),
        ('users', '0012_auto_20200701_2000'),
    ]

    operations = [
    ]
