# Generated by Django 3.0.5 on 2020-04-22 21:10

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=35)),
                ('code', models.CharField(max_length=10)),
                ('course_site', models.URLField()),
                ('credit', models.DecimalField(decimal_places=1, default=0.0, max_digits=3)),
                ('l', models.PositiveSmallIntegerField(blank=True, default=None, null=True)),
                ('t', models.PositiveSmallIntegerField(blank=True, default=None, null=True)),
                ('p', models.PositiveSmallIntegerField(blank=True, default=None, null=True)),
                ('mst', models.PositiveSmallIntegerField(blank=True, default=None, null=True)),
                ('tut_ses', models.PositiveSmallIntegerField(blank=True, default=None, null=True)),
                ('lab_proj', models.PositiveSmallIntegerField(blank=True, default=None, null=True)),
                ('quiz', models.PositiveSmallIntegerField(blank=True, default=None, null=True)),
                ('est', models.PositiveSmallIntegerField(blank=True, default=None, null=True)),
                ('created_date', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('syllabus', models.TextField()),
            ],
            options={
                'verbose_name': 'Course',
                'verbose_name_plural': 'Courses',
            },
        ),
        migrations.CreateModel(
            name='Drivefolder',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=30, null=True)),
                ('drive_id', models.CharField(max_length=33)),
                ('year', models.SmallIntegerField(blank=True, null=True)),
                ('file_name', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name_plural': 'Drive ID',
            },
        ),
        migrations.CreateModel(
            name='Textbook',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128)),
                ('auth_name', models.CharField(max_length=128)),
                ('publisher', models.CharField(max_length=64)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='acad.Course')),
            ],
            options={
                'verbose_name': 'Textbook',
                'verbose_name_plural': 'Textbooks',
            },
        ),
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('year', models.CharField(choices=[('FR', 'Freshman'), ('SO', 'Sophomore'), ('JR', 'Junior Year'), ('SR', 'Senior Year')], max_length=2)),
                ('code', models.CharField(blank=True, default=None, max_length=3, null=True)),
                ('name', models.CharField(blank=True, default=None, max_length=35, null=True)),
                ('created_date', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('course', models.ManyToManyField(blank=True, default=None, to='acad.Course')),
            ],
            options={
                'verbose_name': 'Branch',
                'verbose_name_plural': 'Branches',
            },
        ),
        migrations.CreateModel(
            name='Batch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('num', models.IntegerField()),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='acad.Branch')),
            ],
            options={
                'verbose_name': 'Batch',
                'verbose_name_plural': 'Batchs',
            },
        ),
    ]
