# Generated by Django 3.0.5 on 2020-07-19 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acad', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='is_elective',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='file',
            name='web_content_link',
            field=models.URLField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='branch',
            name='code',
            field=models.CharField(blank=True, default=None, max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='branch',
            name='name',
            field=models.CharField(blank=True, default=None, max_length=75, null=True),
        ),
        migrations.AlterField(
            model_name='branch',
            name='year',
            field=models.CharField(choices=[('FR', 'Freshman'), ('SO', 'Sophomore'), ('JR', 'Junior Year'), ('SR', 'Senior Year')], max_length=15),
        ),
        migrations.AlterField(
            model_name='course',
            name='name',
            field=models.CharField(max_length=75),
        ),
        migrations.AlterField(
            model_name='file',
            name='file',
            field=models.FileField(max_length=255, upload_to='academic_File'),
        ),
        migrations.AlterField(
            model_name='file',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='file',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, null=True),
        ),
    ]
