# Generated by Django 3.0.5 on 2020-07-18 23:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('acad', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batch',
            name='branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='acad.Branch'),
        ),
    ]
