# Generated by Django 3.0.5 on 2020-05-05 02:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('acad', '0003_auto_20200504_2238'),
    ]

    operations = [
        migrations.CreateModel(
            name='FileTags',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=64, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='FileType',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=64, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file', models.FileField(upload_to='academic_File')),
                ('thumnail_image', models.ImageField(upload_to='academic_file')),
                ('date_posted', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('name', models.CharField(max_length=128)),
                ('about', models.TextField(max_length=512, null=True)),
                ('published', models.BooleanField(default=True)),
                ('admin_starred', models.BooleanField(default=False)),
                ('is_reviewed', models.BooleanField(default=False)),
                ('slug', models.SlugField(blank=True, null=True)),
                ('batch', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='acad.Batch')),
                ('branch', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='acad.Branch')),
                ('course', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='acad.Course')),
                ('drivefolder', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='acad.Drivefolder')),
                ('tags', models.ManyToManyField(to='acad.FileTags')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='acad.FileType')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
