# Generated by Django 3.0.5 on 2020-05-05 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acad', '0004_file_filetags_filetype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='thumnail_image',
            field=models.ImageField(upload_to='academic_file_thumbnails'),
        ),
    ]
