# Generated by Django 3.0.5 on 2020-07-28 09:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('acad', '0005_department'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='batch',
            unique_together={('branch', 'num')},
        ),
    ]
