# Generated by Django 3.0.5 on 2020-05-14 17:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('acad', '0006_auto_20200510_1515'),
    ]

    operations = [
        migrations.RenameField(
            model_name='firstyearbatch',
            old_name='GR',
            new_name='gr',
        ),
    ]
