# Generated by Django 3.0.5 on 2020-05-19 00:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("acad", "0007_auto_20200514_1710"),
    ]

    operations = [
        migrations.AddField(
            model_name="academiccalendar",
            name="slug",
            field=models.SlugField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="branch",
            name="batch_of",
            field=models.IntegerField(
                choices=[(2021, 2021), (2022, 2022), (2023, 2023), (2024, 2024)],
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="branch",
            name="passed_out",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="file",
            name="date_modified",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="filetags", name="slug", field=models.SlugField(null=True),
        ),
        migrations.AddField(
            model_name="filetype", name="slug", field=models.SlugField(null=True),
        ),
        migrations.AddField(
            model_name="textbook",
            name="date_modified",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="textbook",
            name="published",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="textbook", name="slug", field=models.SlugField(null=True),
        ),
        migrations.AlterField(
            model_name="file",
            name="about",
            field=models.TextField(blank=True, max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name="file",
            name="branch",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="acad.Branch",
            ),
        ),
        migrations.AlterField(
            model_name="file",
            name="course",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="acad.Course",
            ),
        ),
        migrations.AlterField(
            model_name="file",
            name="thumbnail_image",
            field=models.ImageField(
                blank=True, null=True, upload_to="academic_file_thumbnails"
            ),
        ),
        migrations.AlterField(
            model_name="file",
            name="type",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="acad.FileType",
            ),
        ),
        migrations.AlterField(
            model_name="file",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="textbook",
            name="name",
            field=models.CharField(max_length=128, unique=True),
        ),
    ]
