# Generated by Django 3.0.8 on 2020-07-30 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acad', '0007_semester'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='amazon_url',
            field=models.TextField(blank=True, default=''),
        ),
    ]
