# Generated by Django 3.0.8 on 2020-08-01 19:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('acad', '0007_semester'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='academiccalendar',
            name='type',
        ),
        migrations.AddField(
            model_name='academiccalendar',
            name='semester',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='acad.Semester'),
        ),
    ]
