# Generated by Django 3.0.5 on 2020-06-26 08:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('acad', '0008_auto_20200519_0013'),
    ]

    operations = [
        migrations.RenameField(
            model_name='firstyearbatch',
            old_name='gr',
            new_name='GR',
        ),
    ]
