# Generated by Django 3.0.8 on 2020-08-02 08:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('acad', '0008_auto_20200802_0045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='acad.Batch'),
        ),
        migrations.AlterField(
            model_name='file',
            name='file_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='file',
            name='web_content_link',
            field=models.URLField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='file',
            name='web_view_link',
            field=models.URLField(blank=True, max_length=150, null=True),
        ),
    ]
