# Generated by Django 3.0.5 on 2020-05-23 05:41

import acad.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acad', '0008_auto_20200519_0013'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batch',
            name='num',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='course',
            name='code',
            field=models.CharField(max_length=10, validators=[acad.validators.course_code_validation]),
        ),
        migrations.AlterField(
            model_name='course',
            name='l',
            field=models.DecimalField(blank=True, decimal_places=1, default=None, max_digits=2, null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='p',
            field=models.DecimalField(blank=True, decimal_places=1, default=None, max_digits=2, null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='t',
            field=models.DecimalField(blank=True, decimal_places=1, default=None, max_digits=2, null=True),
        ),
    ]
