# Generated by Django 3.0.8 on 2020-08-02 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acad', '0009_auto_20200802_1419'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='course_site',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='syllabus',
            field=models.TextField(blank=True),
        ),
    ]
