# Generated by Django 3.0.5 on 2020-06-25 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acad', '0009_auto_20200523_0541'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batch',
            name='num',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='course',
            name='code',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='course',
            name='l',
            field=models.PositiveSmallIntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='p',
            field=models.PositiveSmallIntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='t',
            field=models.PositiveSmallIntegerField(blank=True, default=None, null=True),
        ),
    ]
