# Generated by Django 3.0.5 on 2020-07-06 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acad', '0011_auto_20200706_1455'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='file_id',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
