# Generated by Django 3.0.5 on 2020-07-10 19:48

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WifiCreds',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('networkName', models.CharField(blank=True, max_length=20, null=True)),
                ('password', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'verbose_name_plural': 'Wifi Credentials',
                'ordering': ['networkName'],
            },
        ),
        migrations.CreateModel(
            name='WifiCredRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('latitute', models.DecimalField(decimal_places=6, max_digits=9)),
                ('date', models.DateTimeField()),
                ('wificred', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='wifipass.WifiCreds')),
            ],
        ),
    ]
