# Generated by Django 3.0.5 on 2020-07-19 10:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Invite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invite_code', models.CharField(max_length=8, null=True, unique=True)),
                ('can_invite', models.BooleanField(default=True)),
                ('created_date', models.DateTimeField(auto_now=True, null=True)),
                ('invited_users', models.ManyToManyField(blank=True, related_name='Invitees', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='Invite', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
