# Generated by Django 3.0.5 on 2020-07-19 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invite', '0002_auto_20200719_0627'),
    ]

    operations = [
        migrations.AddField(
            model_name='invite',
            name='can_invite',
            field=models.BooleanField(default=False),
        ),
    ]
