# Generated by Django 3.0.5 on 2020-05-01 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='room_no',
        ),
        migrations.AddField(
            model_name='location',
            name='location',
            field=models.URLField(null=True),
        ),
        migrations.AddField(
            model_name='location',
            name='published',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='location',
            name='room',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='location',
            name='building',
            field=models.CharField(choices=[('TAN', 'TAN'), ('LP', 'LP'), ('LT', 'LT'), ('A', 'A Block'), ('B', 'B Block'), ('C', 'C Block'), ('D', 'D Block'), ('E', 'E Block'), ('F', 'F Block'), ('G', 'G Block'), ('COS', 'COS'), ('OAT', 'OAT'), ('LIB', 'Library'), ('MEC', 'Mechanical Block'), ('AUDI', 'Auditorium'), ('GH', 'Guest House'), ('SP', 'Sports Ground'), ('SP', 'Sports Ground')], max_length=4),
        ),
        migrations.AlterField(
            model_name='location',
            name='floor',
            field=models.PositiveSmallIntegerField(null=True),
        ),
    ]
