# Generated by Django 3.0.5 on 2020-07-20 17:39

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('acad', '0002_auto_20200719_1704'),
        ('timetable', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OfflineClass',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('Lecture', 'Lecture'), ('Practical', 'Practical'), ('Tutorial', 'Tutorial')], max_length=10)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('modified_date', models.DateTimeField(null=True)),
                ('day', models.CharField(choices=[('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday'), ('Saturday', 'Saturday'), ('Sunday', 'Sunday')], max_length=10)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('published', models.BooleanField(default=True)),
                ('private', models.BooleanField(default=False)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='acad.Course')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='timetable.Location')),
                ('timetableboard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timetable.TimetableBoard')),
            ],
            options={
                'verbose_name': 'OfflineClass',
                'verbose_name_plural': 'OfflineClasses',
            },
        ),
        migrations.CreateModel(
            name='OnlineClass',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('Lecture', 'Lecture'), ('Practical', 'Practical'), ('Tutorial', 'Tutorial')], max_length=10)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('modified_date', models.DateTimeField(null=True)),
                ('day', models.CharField(choices=[('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday'), ('Saturday', 'Saturday'), ('Sunday', 'Sunday')], max_length=10)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('published', models.BooleanField(default=True)),
                ('private', models.BooleanField(default=False)),
                ('meetingURL', models.URLField(blank=True, null=True)),
                ('isCompleted', models.BooleanField(default=True)),
                ('recordingURL', models.URLField(blank=True, null=True)),
                ('time', models.DateTimeField()),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='acad.Course')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='timetable.Location')),
                ('timetableboard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timetable.TimetableBoard')),
            ],
            options={
                'verbose_name': 'OnlineClass',
                'verbose_name_plural': 'OnlineClasses',
            },
        ),
        migrations.DeleteModel(
            name='Class',
        ),
    ]
