# Generated by Django 3.0.8 on 2020-07-23 15:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0002_auto_20200720_2309'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='onlineclass',
            name='location',
        ),
        migrations.RemoveField(
            model_name='onlineclass',
            name='time',
        ),
    ]
