# Generated by Django 3.0.5 on 2020-05-02 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0002_auto_20200501_2255'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='building',
            field=models.CharField(choices=[('TAN', 'TAN'), ('LP', 'LP'), ('LT', 'LT'), ('A', 'A Block'), ('B', 'B Block'), ('C', 'C Block'), ('D', 'D Block'), ('E', 'E Block'), ('F', 'F Block'), ('G', 'G Block'), ('COS', 'COS'), ('OAT', 'OAT'), ('LIB', 'Library'), ('MEC', 'Mechanical Block'), ('AUDI', 'Auditorium'), ('GH', 'Guest House'), ('SP', 'Sports Ground')], max_length=4),
        ),
    ]
