# Generated by Django 3.0.5 on 2020-05-02 09:14

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0003_auto_20200502_0555'),
    ]

    operations = [
        migrations.CreateModel(
            name='Holidays',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.DateTimeField(max_length=250)),
                ('date', models.DateField()),
            ],
        ),
    ]
