# Generated by Django 3.0.8 on 2020-07-29 11:28

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('acad', '0007_semester'),
        ('timetable', '0003_auto_20200723_2107'),
    ]

    operations = [
        migrations.CreateModel(
            name='Period',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('no', models.PositiveSmallIntegerField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='acad.Semester')),
            ],
        ),
        migrations.RemoveField(
            model_name='onlineclass',
            name='course',
        ),
        migrations.RemoveField(
            model_name='onlineclass',
            name='timetableboard',
        ),
        migrations.RemoveField(
            model_name='timetableboard',
            name='admin_user',
        ),
        migrations.RemoveField(
            model_name='timetableboard',
            name='batch',
        ),
        migrations.DeleteModel(
            name='OfflineClass',
        ),
        migrations.DeleteModel(
            name='OnlineClass',
        ),
        migrations.DeleteModel(
            name='TimetableBoard',
        ),
    ]
