# Generated by Django 3.0.5 on 2020-05-05 20:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0004_holidays'),
    ]

    operations = [
        migrations.RenameField(
            model_name='location',
            old_name='location',
            new_name='location_url',
        ),
    ]
