# Generated by Django 3.0.8 on 2020-07-29 11:57

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('acad', '0007_semester'),
        ('timetable', '0004_auto_20200729_1727'),
    ]

    operations = [
        migrations.CreateModel(
            name='OnlineClass',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('Lecture', 'Lecture'), ('Practical', 'Practical'), ('Tutorial', 'Tutorial')], max_length=10)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('modified_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('day', models.CharField(choices=[('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday'), ('Saturday', 'Saturday'), ('Sunday', 'Sunday')], max_length=10)),
                ('published', models.BooleanField(default=True)),
                ('private', models.BooleanField(default=False)),
                ('meetingURL', models.URLField(blank=True, null=True)),
                ('isCompleted', models.BooleanField(default=True)),
                ('recordingURL', models.URLField(blank=True, null=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='acad.Batch')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='acad.Course')),
                ('period', models.ManyToManyField(to='timetable.Period')),
            ],
            options={
                'verbose_name': 'OnlineClass',
                'verbose_name_plural': 'OnlineClasses',
            },
        ),
        migrations.CreateModel(
            name='OfflineClass',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('Lecture', 'Lecture'), ('Practical', 'Practical'), ('Tutorial', 'Tutorial')], max_length=10)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('modified_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('day', models.CharField(choices=[('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday'), ('Saturday', 'Saturday'), ('Sunday', 'Sunday')], max_length=10)),
                ('published', models.BooleanField(default=True)),
                ('private', models.BooleanField(default=False)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='acad.Batch')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='acad.Course')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='timetable.Location')),
                ('period', models.ManyToManyField(to='timetable.Period')),
            ],
            options={
                'verbose_name': 'OfflineClass',
                'verbose_name_plural': 'OfflineClasses',
            },
        ),
    ]
