# Generated by Django 3.0.8 on 2020-07-29 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0005_offlineclass_onlineclass'),
    ]

    operations = [
        migrations.AlterField(
            model_name='onlineclass',
            name='isCompleted',
            field=models.BooleanField(default=False),
        ),
    ]
