# Generated by Django 3.0.5 on 2020-05-20 11:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0006_auto_20200506_0216'),
    ]

    operations = [
        migrations.RenameField(
            model_name='location',
            old_name='latitute',
            new_name='latitude',
        ),
    ]
