# Generated by Django 3.0.5 on 2020-05-21 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("timetable", "0007_auto_20200520_1114"),
    ]

    operations = [
        migrations.AlterField(
            model_name="class",
            name="day",
            field=models.CharField(
                choices=[
                    ("Monday", "Monday"),
                    ("Tuesday", "Tuesday"),
                    ("Wednesday", "Wednesday"),
                    ("Thursday", "Thursday"),
                    ("Friday", "Friday"),
                    ("Saturday", "Saturday"),
                    ("Sunday", "Sunday"),
                ],
                max_length=10,
            ),
        ),
    ]
