# Generated by Django 3.0.5 on 2020-04-22 21:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Society',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('TECH', 'Technical'), ('CUL', 'Cultural'), ('ADV', 'Adventure'), ('TRAV', 'Travel'), ('SOC', 'Social'), ('BUS', 'Business'), ('ELC', 'Elocution')], max_length=4)),
                ('about', models.CharField(max_length=2000)),
                ('student_head', models.CharField(max_length=100)),
                ('site_link', models.URLField()),
                ('logo', models.ImageField(default='default_society_logo.jpg', upload_to='society_logos')),
                ('image', models.ImageField(default='default_society_photo.jpg', upload_to='society_photos')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Societies',
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('date_posted', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('start_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('end_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('place', models.CharField(max_length=100)),
                ('inCampus', models.BooleanField()),
                ('location', models.URLField(null=True)),
                ('poster_image', models.ImageField(default='event_photo.jpg', upload_to='event_photos')),
                ('external_link', models.URLField()),
                ('society', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Event', related_query_name='Event', to='society.Society')),
            ],
        ),
    ]
