# Generated by Django 3.0.5 on 2020-05-01 22:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0002_auto_20200501_2255'),
        ('society', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='date_modified',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='location_url',
            field=models.URLField(null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='location',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='place',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='timetable.Location'),
        ),
    ]
