# Generated by Django 3.0.5 on 2020-05-20 11:14

from django.db import migrations, models
import profanity.validators


class Migration(migrations.Migration):

    dependencies = [
        ('society', '0002_auto_20200501_2255'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='content',
            field=models.TextField(validators=[profanity.validators.validate_is_profane]),
        ),
        migrations.AlterField(
            model_name='event',
            name='title',
            field=models.CharField(max_length=100, validators=[profanity.validators.validate_is_profane]),
        ),
        migrations.AlterField(
            model_name='society',
            name='about',
            field=models.CharField(max_length=2000, validators=[profanity.validators.validate_is_profane]),
        ),
        migrations.AlterField(
            model_name='society',
            name='name',
            field=models.CharField(max_length=100, validators=[profanity.validators.validate_is_profane]),
        ),
        migrations.AlterField(
            model_name='society',
            name='student_head',
            field=models.CharField(max_length=100, validators=[profanity.validators.validate_is_profane]),
        ),
    ]
