# Generated by Django 3.0.5 on 2020-05-10 15:15

from django.db import migrations


class Migration(migrations.Migration):
    atomic = False
    dependencies = [
        ('members', '0003_member_image'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='VoluteershipApplication',
            new_name='VolunteershipApplication',
        ),
        migrations.RenameModel(
            old_name='VoluteershipType',
            new_name='VolunteershipType',
        ),
    ]
