# Generated by Django 3.0.5 on 2020-05-20 11:14

from django.db import migrations, models
import profanity.validators


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0004_auto_20200510_1515'),
    ]

    operations = [
        migrations.AlterField(
            model_name='volunteershipapplication',
            name='why',
            field=models.TextField(max_length=1000, validators=[profanity.validators.validate_is_profane]),
        ),
    ]
