# Generated by Django 3.0.8 on 2020-07-29 14:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0002_collaborators'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Collaborators',
        ),
    ]
