# Generated by Django 3.0.5 on 2020-04-29 09:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BuzzPost',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('content', models.TextField(max_length=2000)),
                ('date_posted', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('image', models.ImageField(blank=True, null=True, upload_to='buzzPost_photos')),
                ('slug', models.SlugField(blank=True, null=True)),
                ('published', models.BooleanField(default=True)),
                ('is_reviewed', models.BooleanField(default=False)),
                ('editors_choice', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': 'Buzz Posts',
                'ordering': ['-date_posted'],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('created', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('public', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='HumansPost',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('content', models.TextField(max_length=10000)),
                ('date_posted', models.DateTimeField(default=django.utils.timezone.now)),
                ('image', models.ImageField(upload_to='humansoftiet_photos')),
                ('person_name', models.CharField(max_length=50)),
                ('person_detail', models.CharField(max_length=50)),
                ('slug', models.SlugField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Humans of TIET Posts',
                'ordering': ['-date_posted'],
            },
        ),
        migrations.CreateModel(
            name='Miniblog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('about', models.TextField(max_length=10000)),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('header_image', models.ImageField(upload_to='headerimage_miniblog_photos')),
                ('verified', models.BooleanField(default=False)),
                ('points', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'Mini Blogs',
                'ordering': ['-name', 'date_created'],
            },
        ),
        migrations.CreateModel(
            name='Miniblogreview',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.BooleanField(default=False)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('comment', models.TextField(max_length=500)),
                ('miniblog', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='buzz.Miniblog')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Mini Blog Review ',
            },
        ),
        migrations.CreateModel(
            name='BuzzPostReview',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.BooleanField(default=False)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('comment', models.TextField(max_length=500)),
                ('buzzpost', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='buzz.BuzzPost')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Buzz Post',
            },
        ),
        migrations.AddField(
            model_name='buzzpost',
            name='category',
            field=models.ManyToManyField(related_name='BuzzPost', related_query_name='BuzzPost', to='buzz.Category'),
        ),
        migrations.AddField(
            model_name='buzzpost',
            name='miniblog',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='buzz.Miniblog'),
        ),
    ]
